FROM pytorch/pytorch:latest

RUN  apt-get -y update && apt-get -y clean && \
     apt-get -y install vim && \
     pip install --upgrade pip && \
     pip install fastai && \
     pip install -U scikit-learn && \
     pip install scikit-image && \
     pip install jupyterlab && \
     pip install fire && \
     pip install onnx && \
     conda install -y -c conda-forge nodejs && \
     apt-get -y install tmux && \ 
     pip install opencv-python && \ 
     pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu100/index.html && \
     pip install cython && \
     jupyter labextension install @aquirdturtle/collapsible_headings && \
     pip install mlflow && \
     pip install --upgrade mxnet-cu100 gluoncv && \
     pip install nbdev
